[bar]
location = "top"
scale = 1.25
background-opacity = 60

[osd]
enabled = false

[styling.palette]
bg = "#282828"
surface = "#3c3836"
elevated = "#504945"
fg = "#ebdbb2"
fg-muted = "#d5c4a1"
primary = "#83a598"
red = "#fb4934"
yellow = "#fabd2f"
green = "#b8bb26"
blue = "#8ec07c"

[[bar.layout]]
monitor = "*"
left = ["dashboard", "hyprland-workspaces"]
center = ["clock"]
right = ["cava", "ram", "cpu", "volume", "microphone", "systray"]

[modules.hyprland-workspaces]
show-special = false

[modules.dashboard]
dropdown-lock-command = "hyprlock"

[modules.clock]
format = "%a %d %b %H:%M"

[modules.weather]
location = "Trois-Rivières"
units = "metric"
time-format = "24h"

