## Quantum minimal PipeWire
##
## Par défaut, l'Arctis Nova 3P Wireless (USB full speed) force le graphe
## audio entier à 256 échantillons (5,33 ms à 48 kHz), ce qui est trop serré
## sous charge et provoque des sous-dépassements de tampon (xruns).
##
## On impose un plancher de 1024 échantillons (21,3 ms) pour que l'Arctis
## ne puisse plus tirer le quantum vers le bas.

context.properties = {
    default.clock.min-quantum = 1024
}
