ao=pulse

# Profil pour le lancement depuis Qutebrowser
[qutebrowser]
force-window=yes
keep-open=yes
ytdl-format=bestvideo*[height<=?1440]+bestaudio/best
ytdl-raw-options-append=cookies-from-browser=chromium:~/.local/share/qutebrowser
