plugin {
  hy3 {
    # disable gaps when only one window is onscreen
    # 0 - always show gaps
    # 1 - hide gaps with a single window onscreen
    # 2 - 1 but also show the window border
    no_gaps_when_only = 0

    # policy controlling what happens when a node is removed from a group,
    # leaving only a group
    # 0 = remove the nested group
    # 1 = keep the nested group
    # 2 = keep the nested group only if its parent is a tab group
    node_collapse_policy = 2

    # offset from group split direction when only one window is in a group
    group_inset = 10

    # if a tab group will automatically be created for the first window spawned in a workspace
    tab_first_window = false

    # tab group settings
    tabs {
      # height of the tab bar
      height = 22

      # padding between the tab bar and its focused node
      padding = 6

      # the tab bar should animate in/out from the top instead of below the window
      from_top = false

      # radius of tab bar corners
      radius = 6

      # tab bar border width
      border_width = 2 

      # render the window title on the bar
      render_text = true

      # center the window title
      text_center = true

      # font to render the window title with
      text_font = Sans

      # height of the window title
      text_height = 8 

      # left padding of the window title
      text_padding = 3 

      # active tab bar segment colors
      col.active = rgba(33ccff40)
      col.active.border = rgba(33ccffee)
      col.active.text = rgba(ffffffff)

      # focused tab bar segment colors (focused node in unfocused container)
      col.focused = rgba(60606040)
      col.focused.border = rgba(808080ee)
      col.focused.text = rgba(ffffffff)

      # inactive tab bar segment colors
      col.inactive = rgba(30303020)
      col.inactive.border = rgba(606060aa)
      col.inactive.text = rgba(ffffffff)

      # urgent tab bar segment colors
      col.urgent = rgba(ff223340)
      col.urgent.border = rgba(ff2233ee)
      col.urgent.text = rgba(ffffffff)

      # urgent tab bar segment colors
      col.locked = rgba(90903340)
      col.locked.border = rgba(909033ee)
      col.locked.text = rgba(ffffffff)

      # if tab backgrounds should be blurred
      # Blur is only visible when the above colors are not opaque.
      blur = true

      # opacity multiplier for tabs
      # Applies to blur as well as the given colors.
      opacity = 1.0
    }

    # autotiling settings
    autotile {
      # enable autotile
      enable = false

      # make autotile-created groups ephemeral
      ephemeral_groups = true

      # if a window would be squished smaller than this width, a vertical split will be created
      # -1 = never automatically split vertically
      # 0 = always automatically split vertically
      # <number> = pixel width to split at
      trigger_width = 0

      # if a window would be squished smaller than this height, a horizontal split will be created
      # -1 = never automatically split horizontally
      # 0 = always automatically split horizontally
      # <number> = pixel height to split at
      trigger_height = 0

      # a space or comma separated list of workspace ids where autotile should be enabled
      # it's possible to create an exception rule by prefixing the definition with "not:"
      # workspaces = 1,2 # autotiling will only be enabled on workspaces 1 and 2
      # workspaces = not:1,2 # autotiling will be enabled on all workspaces except 1 and 2
      workspaces = all
    }
  }

  split-monitor-workspaces {
    enable_persistent_workspaces = 0
  }
}
