
blur enable
shadows enable
blur_xray disable
corner_radius 10
default_dim_inactive 0
# titlebar_separator enable

layer_effects "waybar" {
    blur enable;
    blur_xray enable;
    blur_ignore_transparent enable;
    shadows enable;
    corner_radius 0;
}

