#!/bin/bash

seconds_now=$(date +"%s")
seconds_2weeks_earlier=$(($seconds_now-86400*15))

date_from=$(date -d @$seconds_2weeks_earlier +"%F")
date_to=$(date -d @$seconds_now +"%F")
timezone='-5'
username=sim.desaulniers@gmail.com
password=$(gpg -d ~/.conky/voipms/voipms-api-key)

CACHE_FILE=~/.cache/voipcdr.json

check_internet_access() { curl -s www.google.com >/dev/null 2>/dev/null; }

check_internet_access && curl -s "https://voip.ms/api/v1/rest.php?\
api_username=$username\
&api_password=$password\
&method=getCDR\
&date_from=$date_from\
&date_to=$date_to\
&noanswer=1\
&timezone=$timezone\
&calltype=incoming" >$CACHE_FILE

# vim: set sts=2 ts=2 sw=2 tw=120 et :

