
[opener]
edit = [
  { run = "vim %s", block = true, for = "unix" },
]

view_image = [
  { run = 'imv -n "$1" "$(dirname "$1")"', desc = "imv", for = "unix" }
]

play_media = [
  { run = 'mpv --keep-open --force-window -- "$1"', desc = "mpv", for = "unix" }
]

inkscape = [
  { run = 'inkscape "$1"', block = false, orphan = true, desc = "Inkscape", for = "unix" }
]

[open]
prepend_rules = [
  { url = "*.svg",    use = [ "inkscape" ]   } ,
  { mime = "video/*",  use = [ "play_media" ] },
  { mime = "image/*", use = [ "view_image" ] } ,
]

